### ISSUE TITLE
Convert to Arduino library

### ISSUE THREAD

**Issue by probonopd** [probonopd/arduino-infrared-pronto#3]
I have been trying to convert the sketch to a library, but it is not working yet.
For reasons not known to me, I get the following error:
```
libraries/Pronto/Pronto.cpp: In function 'void __vector_13()':
libraries/Pronto/Pronto.cpp:91: error: 'ir_toggle' was not declared in this scope
libraries/Pronto/Pronto.cpp:105: error: 'ir_off' was not declared in this scope
```
This might be something releated to running from inside of a ISR?

Pull requests are highly welcome!

**Comment by kdschlosser** [comment]
sorry about the New Issue. I just noticed I could have left a comment here.

**Comment by probonopd** [comment]
See https://github.com/kdschlosser/arduino-infrared-pronto/commit/7195f798b537d82e371b4af6fde6567422590217

**Comment by probonopd** [comment]
Merged your fixed library. Thanks!
