### ISSUE TITLE
Fixed Bug with Library

### ISSUE THREAD

**Issue by kdschlosser** [probonopd/arduino-infrared-pronto#4]
But alas I have not a clue on how to use github. been poking around on how to post the code but can't seem to locate it.

so here it is. First off 

in the example sketch

from this

uint16_t up[] = (Pronto HEX)
 
to this

uint16_t up[78] = (Pronto Hex)

don't think that would have fixed any issues

i did make this change in the Pronto.cpp file
from this
static const uint16_t *ir_code = NULL;
static uint16_t ir_cycle_count = 0;
static uint32_t ir_total_cycle_count = 0;
static uint8_t ir_seq_index = 0;
static uint8_t ir_led_state = 0;

to this
uint16_t ir_cycle_count = 0;
uint32_t ir_total_cycle_count = 0;
uint8_t ir_seq_index = 0;
uint8_t ir_led_state = 0;
uint16_t *ir_code;

and it compiles just fine.. don't have my arduino fully set up yet. so if someone can test this code I would really appreciate it.

Thanks.

**Comment by kdschlosser** [comment]
I don't believe I changed any other code. But i do not know for sure. I can't remember to tell ya the truth. if I knew how to post the code on here. and someone could test the whole thing.

**Comment by kdschlosser** [comment]
I am thinking because you had all the variables set to STATIC (not changing) and had calls to change them. IDK new to C++. learning tho.

**Comment by probonopd** [comment]
Can you please post your working version? The changes
uint16_t ir_cycle_count = 0;
uint32_t ir_total_cycle_count = 0;
uint8_t ir_seq_index = 0;
uint8_t ir_led_state = 0;
uint16_t *ir_code;
do not seem to be sufficient for me to get this to compile. 
Thanks.

**Comment by kdschlosser** [comment]
now if i can just figure out how to receive without blocking. That would be good. I am in the process of making the pin easily changeable. and getting it to work properly on a mega2560

**Comment by probonopd** [comment]
Merged your fixed library. Thanks!
